/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define MAX_TASKS	5
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);


void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);
void enable_processor_faults(void);
__attribute__((naked)) switch_sp_to_psp(void);
uint32_t get_psp_value(void);

void task_delay(uint32_t tick_count);

/* some stack memory calculation */
#define SIZE_TASK_STACK						1024U
#define SIZE_SCHED_STACK					1024U

#define SRAM_START							0X20000000U
#define SIZE_SRAM							( 125 * 1024 )
#define SRAM_END							(SRAM_START + SIZE_SRAM)

#define T1_STACK_START						SRAM_END
#define T2_STACK_START						(SRAM_END - 1 * SIZE_TASK_STACK)
#define T3_STACK_START						(SRAM_END - 2 * SIZE_TASK_STACK)
#define T4_STACK_START						(SRAM_END - 3 * SIZE_TASK_STACK)
#define IDLE_STACK_START					(SRAM_END - 4 * SIZE_TASK_STACK)
#define SCHED_STACK_START					(SRAM_END - 5 * SIZE_TASK_STACK)

#define TICK_HZ 1000U

#define HSI_CLOCK 16000000U
#define SYSTICK_TIM_CLK HSI_CLOCK

#define TASK_RUNNING_STATE 0x00
#define TASK_BLOCKED_STATE 0xFF


uint8_t current_task = 1; //task1 is runing
uint32_t g_tick_count = 0;

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults();



	led_init_all();
	printf("Hello Task Scheduler\n");
	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();
	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();
    /* Loop forever */
	printf("Hello World\n");
	for(;;);
}

void disable_irq_systick()
{
	uint32_t *pSCSR = (uint32_t*)0xE000E010;

	*pSCSR = *pSCSR & ~0x0002;
}

void enable_irq_systick()
{
	uint32_t *pSCSR = (uint32_t*)0xE000E010;

	*pSCSR = *pSCSR | 0x0002;
}

void idle_task(void)
{
	while(1);
}

void task1_handler(void)
{
	while(1)
	{
		//printf("This is task1\n");
		led_on(LED_GREEN);
		delay(DELAY_COUNT_1S);
		led_off(LED_GREEN);
		delay(DELAY_COUNT_1S);
	}
}

void task2_handler(void)
{
	while(1)
	{
		//printf("This is task2\n");
		led_on(LED_RED);
		delay(DELAY_COUNT_500MS);
		led_off(LED_RED);
		delay(DELAY_COUNT_500MS);
	}
}

void task3_handler(void)
{
	while(1)
	{
		//printf("This is task3\n");
		led_on(LED_GREEN_SECOND);
		delay(DELAY_COUNT_250MS);
		led_off(LED_GREEN_SECOND);
		delay(DELAY_COUNT_250MS);
	}
}

void task4_handler(void)
{
	while(1)
	{
		printf("This is task4\n");
	}
}



void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
	uint32_t count_value = SYSTICK_TIM_CLK/tick_hz;

	//load the value in to SVR
	*pSRVR = count_value;

	//do some settings
	*pSCSR |= (1 << 1); //Enable SysTick exception
	*pSCSR |= (1 << 2); //Indicates the clock source, processor clock source

	//enable the systick
	*pSCSR |= (1 << 0); //enable the counter

}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack)
{
	__asm volatile("MSR MSP,R0");
	__asm volatile("MSR MSP,%0": : "r" (sched_top_of_stack) );
	__asm volatile("BX LR");
}

#define DUMMY_XPSR 0X01000000U
void init_tasks_stack(void)
{

	user_tasks[0].current_state = TASK_RUNNING_STATE;
	user_tasks[1].current_state = TASK_RUNNING_STATE;
	user_tasks[2].current_state = TASK_RUNNING_STATE;
	user_tasks[3].current_state = TASK_RUNNING_STATE;
	user_tasks[4].current_state = TASK_RUNNING_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;

	for(int i=0; i<MAX_TASKS; i++)
	{
		pPSP = (uint32_t *) user_tasks[i].psp_value;

		pPSP--; //XPSR
		*pPSP = DUMMY_XPSR; //0X01000000

		pPSP--; //PC
		*pPSP = (uint32_t) user_tasks[i].task_handler; //0X01000000

		pPSP--; //LR
		*pPSP = 0xFFFFFFFD; //0X01000000

		for(int j=0 ; j<13; j++)
		{
			pPSP--;
			*pPSP = 0;
		}

		user_tasks[i].psp_value = (uint32_t)pPSP;
	}

}

void enable_processor_faults(void)
{
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= ( 1 << 16); //mem manage
	*pSHCSR |= ( 1 << 17); //bus fault
	*pSHCSR |= ( 1 << 18); //usage fault
}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void)
{
	current_task++;
	current_task = current_task % MAX_TASKS;
}

__attribute__((naked)) switch_sp_to_psp(void)
{
	//1. initialize the PSP with TASK1 stack start address

	//get the value of psp of current task
	__asm volatile("PUSH {LR}"); // preserve LR which connects back to main()
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0"); //initialize psp
	__asm volatile("POP {LR}"); // pops back LR

	//2. change SP to PSP using CONTROL register.
	__asm volatile("MOV R0,#0X02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}

void task_delay(uint32_t tick_count)
{
	user_tasks[current_task].block_count = g_tick_count + tick_count;
	user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
}

__attribute__((naked)) SysTick_Handler(void)
{
	/*Save the context of current task */

	//1. Get current running task's PSP value
	__asm volatile("MRS R0,PSP");
	//2. Using that PSP value store SF2( R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");
	__asm volatile("PUSH {LR}");
	//3. Save the current value of PSP
	__asm volatile("BL save_psp_value");

	/*Retrieve the context of next task*/
	//1. Decide the next task run
	__asm volatile("BL update_next_task");
	//2. get its past PSP value
	__asm volatile("BL get_psp_value");
	//3. Using that PSP value retrieve SF2( R4 to R11)
	__asm volatile("LDMIA R0!,{R4-R11}");
	//4. update PSP and exit
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}

//2. implement the fault handlers
void HardFault_Handler(void)
{
	printf("Exception : Hardfault\n");
	while(1);
}


void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}
